apiVersion: v1
kind: Namespace
metadata:
  name: produccion
  labels:
    name: produccion
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limit-range-back
  namespace: produccion
spec:
  limits:
  - max:
      memory: 600M
      cpu: 1
    min:
      memory: 100M
      cpu: 0.1
    default:
      memory: 300Mi
      cpu: 0.3
    defaultRequest:
      memory: 100Mi
      cpu: 0.1
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: res-quota-back
  namespace: produccion
spec:
  hard:
    requests.cpu: "5"
    requests.memory: 7Gi