apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Despliegue de componente ms-respuestas"
  name: deployment-ms-respuestas
  namespace: prod-back
  labels:
    app: dep-ms-respuestas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-ms-respuestas
  template:
    metadata:
      labels:
        app: tg-ms-respuestas
    spec:
      containers:
      - name: ms-respuestas
        image: gardinsoft/tg-respuestas:v1.0.2
        resources:
          limits:
            memory: "300Mi"
            cpu: "0.3"
          requests:
            memory: "100Mi"
            cpu: "0.1"
        readinessProbe:
          tcpSocket:
            port: 8003
          initialDelaySeconds: 60
          periodSeconds: 30
        livenessProbe:
          tcpSocket:
            port: 8003
          initialDelaySeconds: 60
          periodSeconds: 30