apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Despliegue de front en la version 1.0.1"
  name: deployment-front
  namespace: produccion
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: gardinsoft/tg-frontend:v1.0.1
        resources:
          limits:
            memory: "300Mi"
            cpu: "0.3"
          requests:
            memory: "100Mi"
            cpu: "0.1"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 30
        
---

apiVersion: v1
kind: Service
metadata:
  name: campus-ms-front
  namespace: produccion
  labels:
    app: ser-front
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80