apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-ms-examenes
  namespace: produccion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-ms-examenes
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-ms-cursos
  namespace: produccion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-ms-cursos
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

---


apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-ms-usuarios
  namespace: produccion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-ms-usuarios
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-ms-respuestas
  namespace: produccion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-ms-respuestas
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-ms-zuul
  namespace: produccion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-ms-zuul
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-front
  namespace: produccion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-front
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80